---


- name: AS3 & Ansible
  hosts: all
  connection: local

  vars:
    provider:
      server: 10.19.31.54
      user: admin
      password: f5Rulez!
      validate_certs: no

  tasks:
  - name: Deploy an app service configuration via AS3 improving success rate
    bigip_appsvcs_extension:
      content: "{{ lookup('file', 'as3_service.json') }}"
      state: present
      provider: "{{ provider }}"
    delegate_to: localhost
